### ISSUE TITLE
Error 500 when editing user profile after installing redmine_rate

### ISSUE THREAD

**Issue by christefano** [rgtk/redmine_rate#1]
When attempting to edit a user's profile (e.g. https://redmine.example/users/53/edit), I get at error 500. Here's what I found in the logs. Any suggestions?

```
Completed 500 Internal Server Error in 5975ms (ActiveRecord: 185.9ms)

ActionView::Template::Error (undefined method `editable?' for #<#<Class:0x000000
07c7bb98>:0x000000034210c8>
Did you mean?  edit_deal_url):
    14:       <%= sort_header_tag('date_in_effect', caption: l(:label_date)) %>
    15:       <%= sort_header_tag('project_id', caption: l(:label_project)) %>
    16:       <th><%= l(:label_rate) %></th>
    17:       <% if editable? %><th></th><% end %>
    18:     </thead>
    19:     <tbody>
    20:       <% @rates.each do |rate| %>
  plugins/redmine_rate/app/views/users/_rates.html.erb:17:in `_plugins_redmine_r
ate_app_views_users__rates_html_erb__3566501657946683686_37130060'
  app/views/common/_tabs.html.erb:17:in `block in _app_views_common__tabs_html_e
rb___877564998240751659_63851420'
  app/views/common/_tabs.html.erb:16:in `each'
  app/views/common/_tabs.html.erb:16:in `_app_views_common__tabs_html_erb___8775
64998240751659_63851420'
  app/helpers/application_helper.rb:345:in `render_tabs'
  app/views/users/edit.html.erb:10:in `_app_views_users_edit_html_erb___42283835
25927610614_27244300'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

**Comment by nounder** [comment]
What's your Redmine version?

**Comment by christefano** [comment]
Oh, sorry! 3.4.3.

**Comment by nounder** [comment]
On fresh Redmine it works fine. Based on info you've provided you are using few more plugins that could lead to some collision. Check out [helper-fix branch](https://github.com/rgtk/redmine_rate/tree/helper-fix), it should resolve your issue.

**Comment by christefano** [comment]
Thanks, I checked out the helper-fix branch and now see this at *users/5* (same URL path as last time)

```
ActionView::Template::Error (undefined method `user_rates_path' for #<#<Class:0x0000000757fe70>:0x007f02e6ac51d0>
Did you mean?  user_path):
    1: <% if User.current.allowed_to_globally?(:view_rates, {}) \
    2:    or RedmineRate.supervisor? %>
    3: <h3><%= link_to l(:label_rates), user_rates_path(@user) %></h3>
    4: <% end %>
  plugins/redmine_rate/app/views/hooks/redmine_rate/_view_account_left_bottom.html.erb:3:in `_plugins_redmine_rate_app_views_hooks_redmine_rate__view_account_left_bottom_html_erb___3179688595015081784_34534020'
  lib/redmine/hook/view_listener.rb:59:in `block (2 levels) in render_on'
  lib/redmine/hook/view_listener.rb:57:in `map'
  lib/redmine/hook/view_listener.rb:57:in `block in render_on'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:96:in `call_hook'
  app/views/users/show.html.erb:45:in `_app_views_users_show_html_erb__3016690396285603687_61543900'
  app/controllers/users_controller.rb:79:in `block (2 levels) in show'
  app/controllers/users_controller.rb:75:in `show'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

**Comment by christefano** [comment]
I think the incompatibility might be with Redmine Contacts: https://www.redmine.org/plugins/redmine_contacts

It defines "editable" on line 326:

```
  def editable?(usr = nil)
    allowed_to?(usr || User.current, :edit_contacts)
  end
```

**Comment by nounder** [comment]
Yes, that's why helper-fix branch renamed this method.

Last error you sent is related to routes. It looks like routes for redmine_rate are not being recognized.

**Comment by nounder** [comment]
This error seems interesting because there should be no interference in this area no matter what plugins you are using.

If you feel adventurous you can open `plugins/redmine_rate/app/views/hooks/redmine_rate/_view_account_left_bottom.html.erb` and replace line 3:
`<h3><%= link_to l(:label_rates), user_rates_path(@user) %></h3>`
with
`<h3><%= link_to l(:label_rates), controller: :rates, action: :index, user_id: @user.id %></h3>`
and check if it works.
